[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "usr-mgmt"
version = "0.1.0"
description = "A user management application made purely for learning the engineering behind production based applications."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Adnan Ahmed", email = "adnnahmed@gmail.com" }
]
maintainers = [
    { name = "Adnan Ahmed", email = "adnnahmed@gmail.com" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "asyncpg",
    "alembic",
    "pydantic",
    "pydantic-settings",
    "python-jose[cryptography]",
    "bcrypt",
    "slowapi",
    "email-validator",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]